# Generated by Django 3.1.5 on 2021-01-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextGenContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('context', models.CharField(max_length=100, verbose_name='Input Text')),
            ],
            options={
                'verbose_name': 'TextGen Context',
                'verbose_name_plural': 'TextGen Context',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TextGenResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('model_type', models.CharField(max_length=100, verbose_name='Model Type')),
                ('gen_text', models.TextField(max_length=500, verbose_name='Generated Text')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='textgen_resp', to='textgen.textgencontext')),
            ],
            options={
                'verbose_name': 'TextGen Response',
                'verbose_name_plural': 'TextGen Response',
                'ordering': ['id'],
            },
        ),
    ]
